version: '3'
services:
  app:
    image: node:20
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run start"
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/mydatabase
  db:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
